# Generated by Django 5.1 on 2024-08-13 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroAnimais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do animal')),
                ('idade', models.CharField(max_length=100, verbose_name='Idade do animal')),
                ('nome_proprietario', models.CharField(max_length=100, verbose_name='Nome do proprietário')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(verbose_name='Data da consulta')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico do animal')),
                ('prescricao', models.TextField(verbose_name='Prescrição médica')),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações')),
                ('animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cadastroanimais', verbose_name='Animal')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('completed', models.BooleanField(default=False, verbose_name='Concluído')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
            },
        ),
    ]
