# Generated by Django 5.1 on 2024-08-20 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroanimais',
            name='caracteristicas',
            field=models.TextField(blank=True, null=True, verbose_name='Características Distintivas'),
        ),
        migrations.AddField(
            model_name='cadastroanimais',
            name='raca',
            field=models.CharField(default='Raça não informada', max_length=100, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='cadastroanimais',
            name='idade',
            field=models.IntegerField(verbose_name='Idade do animal'),
        ),
    ]
