# Generated by Django 5.1 on 2024-08-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_cadastroanimais_caracteristicas_cadastroanimais_raca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizacaoRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_animal', models.CharField(max_length=100, verbose_name='Nome do Animal')),
                ('data_consulta', models.DateField(verbose_name='Data da Consulta')),
                ('diagnostico', models.TextField(verbose_name='Diagnóstico')),
                ('prescricao', models.TextField(verbose_name='Prescrição Médica')),
                ('observacoes', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observações')),
            ],
        ),
    ]
