# Generated by Django 5.1 on 2024-08-22 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_visualizacaoregistro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visualizacaoregistro',
            name='data_consulta',
        ),
        migrations.RemoveField(
            model_name='visualizacaoregistro',
            name='diagnostico',
        ),
        migrations.RemoveField(
            model_name='visualizacaoregistro',
            name='nome_animal',
        ),
        migrations.RemoveField(
            model_name='visualizacaoregistro',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='visualizacaoregistro',
            name='prescricao',
        ),
        migrations.AddField(
            model_name='visualizacaoregistro',
            name='registro_clinico',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visualizacao', to='app.registroclinico'),
        ),
    ]
