# Generated by Django 5.1 on 2024-08-22 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_visualizacaoregistro_data_consulta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VisualizacaoRegistro',
        ),
    ]
