# Generated by Django 5.1 on 2024-08-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_visualizacaoregistro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroanimais',
            name='especie',
            field=models.CharField(choices=[('Gato', 'Gato'), ('Cachorro', 'Cachorro'), ('Pássaro', 'Pássaro'), ('Peixe', 'Peixe'), ('Coelho', 'Coelho'), ('Hamster', 'Hamster'), ('Réptil', 'Réptil'), ('Cavalo', 'Cavalo'), ('Porquinho da Índia', 'Porquinho da Índia'), ('Outro', 'Outro')], default='Outro', max_length=50, verbose_name='Espécie do animal'),
        ),
    ]
